<?php

namespace AppBundle\Repository;

/**
 * CuadranteGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuadranteGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
