<?php

namespace AppBundle\Repository;

/**
 * CuadranteDiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuadranteDiaRepository extends \Doctrine\ORM\EntityRepository
{
}
