<?php

namespace AppBundle\Repository;

/**
 * CuadranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuadranteRepository extends \Doctrine\ORM\EntityRepository
{
}
