<?php

namespace AppBundle\Repository;

/**
 * CuandranteGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuandranteGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
