<?php

namespace AppBundle\Repository;

/**
 * DescansoDiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescansoDiaRepository extends \Doctrine\ORM\EntityRepository
{
}
