<?php

namespace AppBundle\Repository;

/**
 * DiaCuadranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaCuadranteRepository extends \Doctrine\ORM\EntityRepository
{
}
