<?php

namespace AppBundle\Repository;

/**
 * GrupoProfesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoProfesorRepository extends \Doctrine\ORM\EntityRepository
{
}
