<?php

namespace AppBundle\Repository;

/**
 * GruposUsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruposUsuariosRepository extends \Doctrine\ORM\EntityRepository
{
}
