<?php

namespace AppBundle\Repository;

/**
 * GrupoMuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoMuestraRepository extends \Doctrine\ORM\EntityRepository
{
}
