<?php

namespace AppBundle\Repository;

/**
 * ImageOrlaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageOrlaRepository extends \Doctrine\ORM\EntityRepository
{
}
