<?php

namespace AppBundle\Repository;

/**
 * OrlaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrlaRepository extends \Doctrine\ORM\EntityRepository
{
}
