<?php

namespace AppBundle\Repository;

/**
 * UniversidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversidadRepository extends \Doctrine\ORM\EntityRepository
{
}
