<?php

namespace AppBundle\Repository;

/**
 * UsuariosProfesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosProfesRepository extends \Doctrine\ORM\EntityRepository
{

}
