<?php

namespace AppBundle\Repository;

/**
 * UsuariosMuestrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosMuestrasRepository extends \Doctrine\ORM\EntityRepository
{
}
