<?php

namespace AppBundle\Repository;

/**
 * UsuarioMuestraVotarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioMuestraVotarRepository extends \Doctrine\ORM\EntityRepository
{
}
